-- 013_seed_players_full.sql
-- Expands the player pool from the 40-name smoke set to a full draftable pool
-- (~270 additional current NBA players) for a 12+ team mock draft.
--
-- Notes:
--   * Names + positions only. positions uses coarse G/F/C, multi-position allowed.
--   * nba_team / jersey_number left null (not modelled in the draft).
--   * external_id / external_source left null on purpose — these are the hooks a
--     future live provider sync (ESPN/SportRadar via an Edge Function) will backfill.
--   * Idempotent + dedup-safe: each row inserts only if no player with that
--     full_name already exists, so this will not collide with the original 40
--     seed (007b) and can be re-run without creating duplicates.

insert into players (full_name, positions)
select v.full_name, v.positions
from (values
  -- Lead guards
  ('Jamal Murray', ARRAY['G']),
  ('Jalen Green', ARRAY['G']),
  ('Tyrese Maxey', ARRAY['G']),
  ('Darius Garland', ARRAY['G']),
  ('Anfernee Simons', ARRAY['G']),
  ('CJ McCollum', ARRAY['G']),
  ('Fred VanVleet', ARRAY['G']),
  ('Mike Conley', ARRAY['G']),
  ('Chris Paul', ARRAY['G']),
  ('Russell Westbrook', ARRAY['G']),
  ('Bradley Beal', ARRAY['G']),
  ('Zach LaVine', ARRAY['G']),
  ('Jordan Poole', ARRAY['G']),
  ('Coby White', ARRAY['G']),
  ('D''Angelo Russell', ARRAY['G']),
  ('Austin Reaves', ARRAY['G']),
  ('Tyus Jones', ARRAY['G']),
  ('Cole Anthony', ARRAY['G']),
  ('Jalen Suggs', ARRAY['G']),
  ('Kentavious Caldwell-Pope', ARRAY['G']),
  ('Gary Trent Jr.', ARRAY['G']),
  ('Bogdan Bogdanovic', ARRAY['G']),
  ('Malik Monk', ARRAY['G']),
  ('Collin Sexton', ARRAY['G']),
  ('Jordan Clarkson', ARRAY['G']),
  ('Dennis Schroder', ARRAY['G']),
  ('Spencer Dinwiddie', ARRAY['G']),
  ('Payton Pritchard', ARRAY['G']),
  ('Josh Giddey', ARRAY['G']),
  ('Alex Caruso', ARRAY['G']),
  ('Buddy Hield', ARRAY['G']),
  ('Klay Thompson', ARRAY['G']),
  ('Dejounte Murray', ARRAY['G']),
  ('Terry Rozier', ARRAY['G']),
  ('Kyle Lowry', ARRAY['G']),
  ('De''Anthony Melton', ARRAY['G']),
  ('Caris LeVert', ARRAY['G']),
  ('Donte DiVincenzo', ARRAY['G']),
  ('Andrew Nembhard', ARRAY['G']),
  ('T.J. McConnell', ARRAY['G']),
  ('Jaden Ivey', ARRAY['G']),
  ('Cason Wallace', ARRAY['G']),
  ('Keyonte George', ARRAY['G']),
  ('Brandin Podziemski', ARRAY['G']),
  ('Scoot Henderson', ARRAY['G']),
  ('Cam Thomas', ARRAY['G']),
  ('Tre Jones', ARRAY['G']),
  ('Seth Curry', ARRAY['G']),
  ('Luke Kennard', ARRAY['G']),
  ('Tyler Herro', ARRAY['G']),
  ('Quentin Grimes', ARRAY['G']),
  ('Immanuel Quickley', ARRAY['G']),
  ('Malcolm Brogdon', ARRAY['G']),
  ('Marcus Smart', ARRAY['G']),
  ('Davion Mitchell', ARRAY['G']),
  ('Monte Morris', ARRAY['G']),
  ('Cameron Payne', ARRAY['G']),
  ('Dennis Smith Jr.', ARRAY['G']),
  ('Jevon Carter', ARRAY['G']),
  ('Delon Wright', ARRAY['G']),
  ('Aaron Holiday', ARRAY['G']),
  ('Gary Payton II', ARRAY['G']),
  ('Norman Powell', ARRAY['G']),
  ('Max Strus', ARRAY['G','F']),
  ('Isaac Okoro', ARRAY['G','F']),
  ('Ty Jerome', ARRAY['G']),
  ('Sam Merrill', ARRAY['G']),
  ('Max Christie', ARRAY['G']),
  ('Talen Horton-Tucker', ARRAY['G']),
  ('Keon Johnson', ARRAY['G']),
  ('Shaedon Sharpe', ARRAY['G']),
  ('Bilal Coulibaly', ARRAY['G','F']),
  ('Malaki Branham', ARRAY['G']),
  ('Blake Wesley', ARRAY['G']),
  ('Tre Mann', ARRAY['G']),
  ('Malik Beasley', ARRAY['G']),
  ('Gary Harris', ARRAY['G']),
  ('Alec Burks', ARRAY['G']),
  ('Kevin Huerter', ARRAY['G']),
  ('Pat Connaughton', ARRAY['G']),
  ('Ayo Dosunmu', ARRAY['G']),
  ('Marcus Sasser', ARRAY['G']),
  ('Vince Williams Jr.', ARRAY['G']),
  -- Rookies / young guards
  ('Stephon Castle', ARRAY['G']),
  ('Reed Sheppard', ARRAY['G']),
  ('Rob Dillingham', ARRAY['G']),
  ('Devin Carter', ARRAY['G']),
  ('Bub Carrington', ARRAY['G']),
  ('Isaiah Collier', ARRAY['G']),
  ('Jared McCain', ARRAY['G']),
  ('Nikola Topic', ARRAY['G']),
  ('Keon Ellis', ARRAY['G']),
  ('Jaden Hardy', ARRAY['G']),
  ('Julian Strawther', ARRAY['G']),
  ('Andre Jackson Jr.', ARRAY['G']),
  ('AJ Green', ARRAY['G']),
  ('Jaden Springer', ARRAY['G']),
  ('Kobe Bufkin', ARRAY['G']),
  ('Jordan Hawkins', ARRAY['G']),
  ('Colby Jones', ARRAY['G']),
  ('Nick Smith Jr.', ARRAY['G']),
  ('Terrence Shannon Jr.', ARRAY['G']),
  ('Jamal Shead', ARRAY['G']),
  ('Baylor Scheierman', ARRAY['G']),
  ('Jared Butler', ARRAY['G']),
  -- Wings
  ('Gradey Dick', ARRAY['G','F']),
  ('Josh Hart', ARRAY['G','F']),
  ('RJ Barrett', ARRAY['G','F']),
  ('Bennedict Mathurin', ARRAY['G','F']),
  ('Jalen Williams', ARRAY['G','F']),
  ('Lu Dort', ARRAY['G','F']),
  ('Amen Thompson', ARRAY['G','F']),
  ('Ausar Thompson', ARRAY['G','F']),
  ('Devin Vassell', ARRAY['G','F']),
  ('Kelly Oubre Jr.', ARRAY['G','F']),
  ('Grayson Allen', ARRAY['G']),
  ('Josh Green', ARRAY['G','F']),
  ('Duncan Robinson', ARRAY['F']),
  ('Landry Shamet', ARRAY['G']),
  ('Cam Whitmore', ARRAY['F']),
  ('Ochai Agbaji', ARRAY['G','F']),
  ('Matisse Thybulle', ARRAY['G','F']),
  ('Christian Braun', ARRAY['G','F']),
  ('Moses Moody', ARRAY['G','F']),
  ('DeMar DeRozan', ARRAY['G','F']),
  ('Khris Middleton', ARRAY['F']),
  ('Brandon Miller', ARRAY['F']),
  ('Jaime Jaquez Jr.', ARRAY['G','F']),
  ('Jaylen Wells', ARRAY['G','F']),
  ('Joe Ingles', ARRAY['F']),
  ('Tristan da Silva', ARRAY['F']),
  ('Ryan Dunn', ARRAY['F']),
  ('Kris Murray', ARRAY['F']),
  ('Brice Sensabaugh', ARRAY['F']),
  ('Leonard Miller', ARRAY['F']),
  ('Trendon Watford', ARRAY['F']),
  ('Jalen McDaniels', ARRAY['F']),
  ('Zeke Nnaji', ARRAY['F']),
  -- Forwards
  ('Jaren Jackson Jr.', ARRAY['F','C']),
  ('OG Anunoby', ARRAY['F']),
  ('Mikal Bridges', ARRAY['F']),
  ('Miles Bridges', ARRAY['F']),
  ('Brandon Ingram', ARRAY['F']),
  ('Michael Porter Jr.', ARRAY['F']),
  ('Aaron Gordon', ARRAY['F']),
  ('Kyle Kuzma', ARRAY['F']),
  ('Tobias Harris', ARRAY['F']),
  ('Jerami Grant', ARRAY['F']),
  ('Harrison Barnes', ARRAY['F']),
  ('Bojan Bogdanovic', ARRAY['F']),
  ('PJ Washington', ARRAY['F']),
  ('Grant Williams', ARRAY['F']),
  ('Cameron Johnson', ARRAY['F']),
  ('Dorian Finney-Smith', ARRAY['F']),
  ('Royce O''Neale', ARRAY['F']),
  ('Nicolas Batum', ARRAY['F']),
  ('Naji Marshall', ARRAY['F']),
  ('Herbert Jones', ARRAY['F']),
  ('Trey Murphy III', ARRAY['F']),
  ('Keldon Johnson', ARRAY['F']),
  ('Jeremy Sochan', ARRAY['F']),
  ('Rui Hachimura', ARRAY['F']),
  ('Deni Avdija', ARRAY['F']),
  ('Jaden McDaniels', ARRAY['F']),
  ('Kyle Anderson', ARRAY['F']),
  ('Taurean Prince', ARRAY['F']),
  ('Obi Toppin', ARRAY['F']),
  ('Julius Randle', ARRAY['F']),
  ('Dillon Brooks', ARRAY['F']),
  ('Peyton Watson', ARRAY['F']),
  ('Jonathan Kuminga', ARRAY['F']),
  ('Patrick Williams', ARRAY['F']),
  ('Jabari Smith Jr.', ARRAY['F']),
  ('Tari Eason', ARRAY['F']),
  ('GG Jackson', ARRAY['F']),
  ('Jalen Johnson', ARRAY['F']),
  ('De''Andre Hunter', ARRAY['F']),
  ('Saddiq Bey', ARRAY['F']),
  ('Toumani Camara', ARRAY['F']),
  ('Aaron Nesmith', ARRAY['F']),
  ('Ziaire Williams', ARRAY['F']),
  ('Cam Reddish', ARRAY['F']),
  ('Corey Kispert', ARRAY['F']),
  ('Jarred Vanderbilt', ARRAY['F']),
  ('Draymond Green', ARRAY['F']),
  ('Keegan Murray', ARRAY['F']),
  ('Lauri Markkanen', ARRAY['F']),
  ('Simone Fontecchio', ARRAY['F']),
  ('Caleb Martin', ARRAY['F']),
  ('Cody Martin', ARRAY['F']),
  ('Georges Niang', ARRAY['F']),
  ('Dean Wade', ARRAY['F']),
  ('Nikola Jovic', ARRAY['F']),
  ('Jae''Sean Tate', ARRAY['F']),
  ('Josh Okogie', ARRAY['G','F']),
  ('Dalton Knecht', ARRAY['G','F']),
  ('Kyshawn George', ARRAY['G','F']),
  ('Zaccharie Risacher', ARRAY['F']),
  ('Marvin Bagley III', ARRAY['F','C']),
  ('Jonathan Isaac', ARRAY['F']),
  ('Trayce Jackson-Davis', ARRAY['F','C']),
  ('Xavier Tillman', ARRAY['F']),
  ('Chuma Okeke', ARRAY['F']),
  ('Jonathan Mogbo', ARRAY['F']),
  ('Julian Champagnie', ARRAY['F']),
  ('Trey Lyles', ARRAY['F']),
  ('Dario Saric', ARRAY['F']),
  ('Kevin Love', ARRAY['F']),
  ('Sandro Mamukelashvili', ARRAY['F']),
  ('Precious Achiuwa', ARRAY['F','C']),
  ('Larry Nance Jr.', ARRAY['F','C']),
  ('Santi Aldama', ARRAY['F','C']),
  ('John Collins', ARRAY['F','C']),
  ('Bobby Portis', ARRAY['F','C']),
  ('Isaiah Stewart', ARRAY['F','C']),
  ('Jalen Smith', ARRAY['F','C']),
  ('Kelly Olynyk', ARRAY['F','C']),
  ('Kyle Filipowski', ARRAY['F']),
  -- Centers
  ('Naz Reid', ARRAY['F','C']),
  ('Al Horford', ARRAY['F','C']),
  ('Wendell Carter Jr.', ARRAY['F','C']),
  ('Onyeka Okongwu', ARRAY['F','C']),
  ('Jarrett Allen', ARRAY['C']),
  ('Myles Turner', ARRAY['C']),
  ('Brook Lopez', ARRAY['C']),
  ('Clint Capela', ARRAY['C']),
  ('Nikola Vucevic', ARRAY['C']),
  ('Jusuf Nurkic', ARRAY['C']),
  ('Deandre Ayton', ARRAY['C']),
  ('Jonas Valanciunas', ARRAY['C']),
  ('Ivica Zubac', ARRAY['C']),
  ('Nic Claxton', ARRAY['C']),
  ('Mitchell Robinson', ARRAY['C']),
  ('Isaiah Hartenstein', ARRAY['C']),
  ('Daniel Gafford', ARRAY['C']),
  ('Dereck Lively II', ARRAY['C']),
  ('Robert Williams III', ARRAY['C']),
  ('Mark Williams', ARRAY['C']),
  ('Jaylin Williams', ARRAY['F','C']),
  ('Zach Edey', ARRAY['C']),
  ('Donovan Clingan', ARRAY['C']),
  ('Yves Missi', ARRAY['C']),
  ('Kel''el Ware', ARRAY['C']),
  ('Walker Kessler', ARRAY['C']),
  ('Andre Drummond', ARRAY['C']),
  ('Steven Adams', ARRAY['C']),
  ('Mason Plumlee', ARRAY['C']),
  ('Jericho Sims', ARRAY['C']),
  ('Day''Ron Sharpe', ARRAY['C']),
  ('Moritz Wagner', ARRAY['F','C']),
  ('Luke Kornet', ARRAY['C']),
  ('Neemias Queta', ARRAY['C']),
  ('Nick Richards', ARRAY['C']),
  ('Jaxson Hayes', ARRAY['C']),
  ('Isaiah Jackson', ARRAY['C']),
  ('Jalen Duren', ARRAY['C']),
  ('Goga Bitadze', ARRAY['C']),
  ('Thomas Bryant', ARRAY['C']),
  ('Kevon Looney', ARRAY['C']),
  ('Charles Bassey', ARRAY['C']),
  ('Zach Collins', ARRAY['F','C']),
  ('Drew Eubanks', ARRAY['C'])
) as v(full_name, positions)
where not exists (
  select 1 from players p where p.full_name = v.full_name
);
